[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Magnetostatics = "e551bd30-f216-4325-9989-532520624021"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[sources]
Magnetostatics = {path = ".."}
