name = "Magnetostatics"
uuid = "e551bd30-f216-4325-9989-532520624021"
version = "0.1.0"
authors = ["Hongyang Zhou <hyzhou@umich.edu>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FFTW = "1.10.0"
LinearAlgebra = "1.12.0"
PrecompileTools = "1.3.3"
SpecialFunctions = "2.6.1"
StaticArrays = "1.9.16"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
