[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Magnetostatics = "e551bd30-f216-4325-9989-532520624021"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocumenterVitepress = "0.2"
