[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
Magnetostatics = "e551bd30-f216-4325-9989-532520624021"

[compat]
DocumenterVitepress = "0.2"
